In [95]:
class P:
    __width=None
    __height=None
    
    def set_values(self,height,width):
        self.__height=height
        self.__width=width
    def get_height(self):
        return self.__height
    def get_width(self):
        return self.__width
class Rectangle(P):
    def area(self):
        return self.get_height()* self.get_width()
class Triangle(P):
    def area(self):
        return self.get_height()*self.get_width()/2

rect=Rectangle()

tri=Triangle()

rect.set_values(int(input()),int(input()))
tri.set_values(89,63)

print(rect.area())
print(tri.area())
    
    

23
45
1035
2803.5


## Numpy

- numpy num(numerical)  py(python)
- scientific calu or math cal
- ndarray
- array oriented computing

In [ ]:
# Array
- mutable
- index
- homogenous (same datatypes allowed)

In [ ]:
- fast
- covenient
- less memory

In [ ]:
- one dimentional
- two dimentional
- multi dimentio

In [8]:
import numpy

In [10]:
print(dir(numpy),end="")

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_arg', '_distributor_init', '_globals', '_mat', '_mklinit', '_pytestteste

In [22]:
import numpy as np

a=np.array([1,2,3,4,6,7,8,9])
a

array([1, 2, 3, 4, 6, 7, 8, 9])

In [23]:
a.dtype

dtype('int32')

In [31]:
print(a[0])
print(a[1])
print(a[1:3])
print(a[-1])
print(a[[3,6]])
print(a[1::2])

1
2
[2 3]
9
[4 8]
[2 4 7 9]


In [37]:
np.arange(1,10,2)
#np.arange(12)

array([1, 3, 5, 7, 9])

In [39]:
c=range(1,100)
%timeit [i**3 for i in c]

62.6 µs ± 20.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [41]:
c_numpy=np.arange(1000)
%timeit c_numpy**3

5.65 µs ± 1.42 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [52]:
d=range(1,1000)
e=[i**2 for i in range(1,1000)]
%timeit list(map(lambda x,y : x*y,d,e))

210 µs ± 59.7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [51]:
d_numpy=np.array(d)
e_numpy=np.array(e)

%timeit d_numpy * e_numpy

2.73 µs ± 677 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [53]:
# two dimentionals array
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [55]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
a.ndim # for dimentionals function

2

In [73]:
a[0:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
[5,6]
[8,9]

In [74]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
# zero matices
# one matrices
# identity matrices
# diagnoal matices
# transpose matrices
# inveres

In [77]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [81]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [83]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [85]:
np.full((3,3),4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [86]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [91]:
a=np.array([[1,2],[4,5]])
a

array([[1, 2],
       [4, 5]])

In [92]:
a.T

array([[1, 4],
       [2, 5]])

In [93]:
a=np.array([[1,2],[3,4]])

1/ad-bc[d -b]
       [-c a]

IndentationError: unexpected indent (<ipython-input-93-a3febfae2090>, line 4)

In [94]:
np.linalg.inv(a)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])